[nrf fromlist] Tfm rework pcd memory locking
nrfconnect/sdk-trusted-firmware-m pull request #172
Opened 2024-10-15 08:09 UTC by MarkusLassila

PCD memory area used with nRF53 to be locked with TF-M, instead of bootloader.

Upstream PR: https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/31827
Includes missing header file.

---
Conflicting noup change (and further conflict) reverted and cherry-picked from upstream.

2024-10-15 11:48 UTC, tomi-font requested changes
[This commit](https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/172/commits/f302c193ddfbea4f8f2bb7a25f1df83f85b92306) is missing a `cherry picked from` line. Otherwise looks good.

2024-10-18 08:48 UTC, MarkusLassila commented
> [This commit](https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/172/commits/f302c193ddfbea4f8f2bb7a25f1df83f85b92306) is missing a `cherry picked from` line. Otherwise looks good.

Due to new conflicting changes, I needed to do the revert / cherry-pick from the scratch. Please re-review.

2024-10-18 09:54 UTC, MarkusLassila commented
> There's parallel work ongoing ([nrfconnect/sdk-nrf#17685](https://github.com/nrfconnect/sdk-nrf/pull/17685)) which I'm hoping to get merged soon (sooner than this), so let's wait for that to be in first as I imagine both PRs won't be compatible ? (sorry - should've mentioned that earlier) Or how soon do you think you can get this in?

That depends on the reviewers. The PR itself has been ready for a while.

2024-10-21 08:42 UTC, tomi-font approved these changes

2024-10-23 06:33 UTC, merged