[nrf temphack] Add configurable stack size for crypto partition.
nrfconnect/sdk-trusted-firmware-m pull request #58
Opened 2022-08-12 09:55 UTC by joerchan

Add configurable stack size for the TF-M crypto partition.
This is a temporary method of adding this configuration since the
upstream TF-M implementation for this feature could not be backported
in a clean way.

Should be replaced by the upstream feature in future TF-M upmerge:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/16125

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

2022-08-12 10:22 UTC, frkv approved these changes
LGTM

2022-08-12 10:58 UTC, Vge0rge approved these changes

2022-08-23 10:24 UTC, SebastianBoe commented
[nrf temphack] is no longer a permitted sauce tag unless I am mistaken.

2022-08-23 10:27 UTC, SebastianBoe commented
I think we want to use:



nrf fromlist] | patches submitted to upstream for review, and revisions to them

2022-08-23 10:28 UTC, SebastianBoe requested changes
Changes requested

2022-08-23 14:52 UTC, joerchan commented
> I think we want to use:
> 
> nrf fromlist] | patches submitted to upstream for review, and revisions to them

It is not submitted upstream. There is a PR in upstream, that I cannot backport, due to the amount of conflicts. Which is why I am doing a temporary hack instead. It should be reverted on the next upmerge.
I can use noup / fromlist instead, but I feel like that is just making it more confusing, temphack is the correct description for it.
Unless we are also not allowing temporary hacks to be done?

2022-08-24 06:49 UTC, SebastianBoe commented
I agree that temphack is the correct description, but unfortunately it is no longer permitted.

The second-best description is noup with a commit message with the explanation that you just gave.

2022-08-24 09:53 UTC, joerchan commented
Updated commit message to use nrf noup tag.

2022-08-25 11:47 UTC, SebastianBoe approved these changes

2022-08-25 11:47 UTC, merged