[nrf toup] nrf: Replace deprecated enum for timer prescaler
nrfconnect/sdk-trusted-firmware-m pull request #65
Opened 2022-09-12 14:27 UTC by awojasinski-nordicsemi

This commit replaces deprecated nrf_timer_frequency_t enum with new numerical value.

Signed-off-by: Adam Wojasinski <adam.wojasinski@nordicsemi.no>

2022-09-13 08:24 UTC, SebastianBoe commented
Link to PR that deprecates the enum ?

2022-09-13 08:38 UTC, SebastianBoe requested changes
We will await nrfx 2.10 which has a macro so we don't have to hardcode the prescaler.

2022-09-13 08:39 UTC, joerchan commented on platform/ext/target/lairdconnectivity/common/core/plat_test.c
> +    // Base frequency is 16MHz, in order to get 1MHz prescaler need to be set to 4
Use /* */ style commenting.

2023-01-23 10:57 UTC, joerchan commented
@awojasinski-nordicsemi Do you have PR to update NCS manifest file?

2023-01-23 10:58 UTC, awojasinski-nordicsemi commented
@SebastianBoe as we agreed replaced hard-coded value with one calculated by macro from nrfx 2.10

2023-01-23 10:59 UTC, awojasinski-nordicsemi commented
@joerchan not at this moment, I'll create one

2023-01-23 13:10 UTC, joerchan approved these changes

2023-01-26 14:16 UTC, SebastianBoe approved these changes

2023-01-26 14:27 UTC, merged