Upmerge branch 2022.12.13
nrfconnect/sdk-trusted-firmware-m pull request #81
Opened 2022-12-14 11:19 UTC by cvinayak

Merge to upstream commit https://github.com/zephyrproject-rtos/trusted-firmware-m/commit/887798f6e67203e6a77059a86edf41bb136a3c0b

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

2022-12-15 08:30 UTC, SebastianBoe approved these changes

2023-01-04 10:34 UTC, joerchan requested changes
This one is missing nrf tags,

2023-01-04 10:55 UTC, joerchan approved these changes

2023-01-04 10:57 UTC, SebastianBoe approved these changes

2023-01-10 12:56 UTC, nordicjm approved these changes

2023-01-11 12:23 UTC, merged