[nrf toup] Add UART flow control support
nrfconnect/sdk-trusted-firmware-m pull request #89
Opened 2023-04-03 15:03 UTC by joerchan

Add UART flow control for nordic platform UART driver.
Add generic platform support for respecting platform specific UART configuartions.

2023-04-04 15:29 UTC, Vge0rge commented on platform/ext/target/nordic_nrf/common/core/cmsis_drivers/Driver_USART.c
> +            .hwfc = RTE_USART##idx##_HWFC,                                \
nit: Make the = value aligned with the following lines.

2023-04-04 15:35 UTC, Vge0rge commented on platform/ext/target/nordic_nrf/nrf5340dk_nrf5340_cpuapp/RTE_Device.h
> +#define   RTE_USART2_HWFC               NRF_UARTE_HWFC_DISABLED
Is that not meant to be USART3_HWFC?

2023-04-04 15:36 UTC, Vge0rge commented on platform/ext/target/nordic_nrf/nrf9160dk_nrf9160/RTE_Device.h
> +#define   RTE_USART2_HWFC               NRF_UARTE_HWFC_DISABLED
Same as before.

2023-04-10 11:50 UTC, Vge0rge approved these changes

2023-04-12 09:57 UTC, SebastianBoe requested changes
toup is not allowed IIRC

2023-04-12 10:06 UTC, SebastianBoe approved these changes

2023-04-14 10:39 UTC, joerchan commented
> toup is not allowed IIRC

This was temporary, the patches have been submitted upstream, changed to fromlist.

2023-04-18 11:10 UTC, merged